script:
  host: script_ip
  port: script_port
rvision:
  tenant_1:
    token: api_token_rvision1
  tenant_2:
    token: api_token_rvision2
  protocol: https
alert:
  alert_id_tag: kuma_alert_id
  kuma_url_tag: kuma_url
  category: KUMA_ALERT
kuma:
  host: kuma_host:7223
  token: api_token_kuma
