script:
  host: script_ip
  port: script_port
rvision:
  tenant_1:
    host: rvision1_ip
    tenant_1_name: tenant1_name
  tenant_2:
    host: rvision2_ip
    tenant_2_name: tenant2_name
  protocol: https
alert:
  alert_id_tag: kuma_alert_id
  kuma_url_tag: kuma_url
  category: KUMA_ALERT
kuma:
  host: kuma_host:7223
